//
//  DBConstantString.h
//  DeepBooks
//
//  Created by 王祥伟 on 2025/7/22.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN



@interface DBConstantString : NSObject

@property (nonatomic, copy) NSString *ks_back;
@property (nonatomic, copy) NSString *ks_under10kWords;
@property (nonatomic, copy) NSString *ks_popular;
@property (nonatomic, copy) NSString *ks_disclaimer;
@property (nonatomic, copy) NSString *ks_reading;
@property (nonatomic, copy) NSString *ks_uniqueNicknameRequired;
@property (nonatomic, copy) NSString *ks_urlProtagonistFormat;
@property (nonatomic, copy) NSString *ks_settings;
@property (nonatomic, copy) NSString *ks_noSearchHistory;
@property (nonatomic, copy) NSString *ks_reviews;
@property (nonatomic, copy) NSString *ks_netCacheCleared;
@property (nonatomic, copy) NSString *ks_enterTitleOrAuthor;
@property (nonatomic, copy) NSString *ks_clearCache;
@property (nonatomic, copy) NSString *ks_pointsSuffix;
@property (nonatomic, copy) NSString *ks_selectedCount;
@property (nonatomic, copy) NSString *ks_fiveStar;
@property (nonatomic, copy) NSString *ks_home;
@property (nonatomic, copy) NSString *ks_read;
@property (nonatomic, copy) NSString *ks_unavailable;
@property (nonatomic, copy) NSString *ks_unfold;
@property (nonatomic, copy) NSString *ks_general;
@property (nonatomic, copy) NSString *ks_enterPhoneNumber;
@property (nonatomic, copy) NSString *ks_sortBy;
@property (nonatomic, copy) NSString *ks_clear;
@property (nonatomic, copy) NSString *ks_categories;
@property (nonatomic, copy) NSString *ks_noResults;
@property (nonatomic, copy) NSString *ks_guidelines;
@property (nonatomic, copy) NSString *ks_agreementHint;
@property (nonatomic, copy) NSString *ks_enterNewPassword;
@property (nonatomic, copy) NSString *ks_maxScoreError;
@property (nonatomic, copy) NSString *ks_gotIt;
@property (nonatomic, copy) NSString *ks_violationProcessTime;
@property (nonatomic, copy) NSString *ks_flip;
@property (nonatomic, copy) NSString *ks_readsFormat;
@property (nonatomic, copy) NSString *ks_signUp;
@property (nonatomic, copy) NSString *ks_pending;
@property (nonatomic, copy) NSString *ks_poor;
@property (nonatomic, copy) NSString *ks_cellularDownloadWarning;
@property (nonatomic, copy) NSString *ks_awesome;
@property (nonatomic, copy) NSString *ks_active;
@property (nonatomic, copy) NSString *ks_clearBookCacheConfirm;
@property (nonatomic, copy) NSString *ks_yesterdayTimeFormat;
@property (nonatomic, copy) NSString *ks_searchBooksHint;
@property (nonatomic, copy) NSString *ks_rateUsPrompt;
@property (nonatomic, copy) NSString *ks_clearAllChaptersWarning;
@property (nonatomic, copy) NSString *ks_uploadSuccess;
@property (nonatomic, copy) NSString *ks_feedbackOpinion;
@property (nonatomic, copy) NSString *ks_chapterListError;
@property (nonatomic, copy) NSString *ks_updateNow;
@property (nonatomic, copy) NSString *ks_requestFulfilledStatus;
@property (nonatomic, copy) NSString *ks_readingPreferenceHint;
@property (nonatomic, copy) NSString *ks_replySuffix;
@property (nonatomic, copy) NSString *ks_block;
@property (nonatomic, copy) NSString *ks_later;
@property (nonatomic, copy) NSString *ks_rateUs;
@property (nonatomic, copy) NSString *ks_searchResults;
@property (nonatomic, copy) NSString *ks_blueLightFilter;
@property (nonatomic, copy) NSString *ks_eyeCareMode;
@property (nonatomic, copy) NSString *ks_yes;
@property (nonatomic, copy) NSString *ks_ok;
@property (nonatomic, copy) NSString *ks_belowMinScore;
@property (nonatomic, copy) NSString *ks_changeCoverConfirm;
@property (nonatomic, copy) NSString *ks_noCachedBooks;
@property (nonatomic, copy) NSString *ks_me;
@property (nonatomic, copy) NSString *ks_verificationCodeSent;
@property (nonatomic, copy) NSString *ks_notDownloaded;
@property (nonatomic, copy) NSString *ks_noReadingHistory;
@property (nonatomic, copy) NSString *ks_readingModesHint;
@property (nonatomic, copy) NSString *ks_rateFirst;
@property (nonatomic, copy) NSString *ks_feedback;
@property (nonatomic, copy) NSString *ks_noBooks;
@property (nonatomic, copy) NSString *ks_requiredAuthorField;
@property (nonatomic, copy) NSString *ks_thirtyMinutes;
@property (nonatomic, copy) NSString *ks_blockSuccess;
@property (nonatomic, copy) NSString *ks_wordCountFormat;
@property (nonatomic, copy) NSString *ks_share;
@property (nonatomic, copy) NSString *ks_peopleSuffix;
@property (nonatomic, copy) NSString *ks_tenThousandSuffix;
@property (nonatomic, copy) NSString *ks_tenThousand;
@property (nonatomic, copy) NSString *ks_phone;
@property (nonatomic, copy) NSString *ks_clearBookCache;
@property (nonatomic, copy) NSString *ks_totalCount;
@property (nonatomic, copy) NSString *ks_timer;
@property (nonatomic, copy) NSString *ks_deleteAccount;
@property (nonatomic, copy) NSString *ks_qrCodeScanHint;
@property (nonatomic, copy) NSString *ks_readingMinutes;
@property (nonatomic, copy) NSString *ks_noRequests;
@property (nonatomic, copy) NSString *ks_emptyChapter;
@property (nonatomic, copy) NSString *ks_invalidPassword;
@property (nonatomic, copy) NSString *ks_empty;
@property (nonatomic, copy) NSString *ks_skip;
@property (nonatomic, copy) NSString *ks_passwordChanged;
@property (nonatomic, copy) NSString *ks_unread;
@property (nonatomic, copy) NSString *ks_syncShelf;
@property (nonatomic, copy) NSString *ks_searchAll;
@property (nonatomic, copy) NSString *ks_minMaxScoreError;
@property (nonatomic, copy) NSString *ks_details;
@property (nonatomic, copy) NSString *ks_writeReview;
@property (nonatomic, copy) NSString *ks_contact;
@property (nonatomic, copy) NSString *ks_sixtyMinutes;
@property (nonatomic, copy) NSString *ks_completed;
@property (nonatomic, copy) NSString *ks_reply;
@property (nonatomic, copy) NSString *ks_about;
@property (nonatomic, copy) NSString *ks_removedFromShelf;
@property (nonatomic, copy) NSString *ks_chapterFormat;
@property (nonatomic, copy) NSString *ks_enterSearchText;
@property (nonatomic, copy) NSString *ks_saveForLater;
@property (nonatomic, copy) NSString *ks_viewAllReplies;
@property (nonatomic, copy) NSString *ks_chapters;
@property (nonatomic, copy) NSString *ks_bookmarks;
@property (nonatomic, copy) NSString *ks_passwordMismatch;
@property (nonatomic, copy) NSString *ks_noneSelected;
@property (nonatomic, copy) NSString *ks_heitiFont;
@property (nonatomic, copy) NSString *ks_history;
@property (nonatomic, copy) NSString *ks_book;
@property (nonatomic, copy) NSString *ks_addToShelfFailed;
@property (nonatomic, copy) NSString *ks_registrationAgreement;
@property (nonatomic, copy) NSString *ks_speed;
@property (nonatomic, copy) NSString *ks_standard;
@property (nonatomic, copy) NSString *ks_nickname;
@property (nonatomic, copy) NSString *ks_byAuthorFormat;
@property (nonatomic, copy) NSString *ks_quickRate;
@property (nonatomic, copy) NSString *ks_viewBookstore;
@property (nonatomic, copy) NSString *ks_fontError;
@property (nonatomic, copy) NSString *ks_terms;
@property (nonatomic, copy) NSString *ks_confirm;
@property (nonatomic, copy) NSString *ks_lastChapterReached;
@property (nonatomic, copy) NSString *ks_enterOriginalUrl;
@property (nonatomic, copy) NSString *ks_commentGuidelines;
@property (nonatomic, copy) NSString *ks_enterVerificationCode;
@property (nonatomic, copy) NSString *ks_noUpdates;
@property (nonatomic, copy) NSString *ks_systemFont;
@property (nonatomic, copy) NSString *ks_disgusting;
@property (nonatomic, copy) NSString *ks_yesterday;
@property (nonatomic, copy) NSString *ks_ongoing;
@property (nonatomic, copy) NSString *ks_cached;
@property (nonatomic, copy) NSString *ks_viewReviews;
@property (nonatomic, copy) NSString *ks_xingkaiBold;
@property (nonatomic, copy) NSString *ks_accountRecoveryNotice;
@property (nonatomic, copy) NSString *ks_qrCodeSaveFailed;
@property (nonatomic, copy) NSString *ks_ascending;
@property (nonatomic, copy) NSString *ks_store;
@property (nonatomic, copy) NSString *ks_describeIssuePrompt;
@property (nonatomic, copy) NSString *ks_readPercentage;
@property (nonatomic, copy) NSString *ks_changePassword;
@property (nonatomic, copy) NSString *ks_delete;
@property (nonatomic, copy) NSString *ks_selectAll;
@property (nonatomic, copy) NSString *ks_bookTitleFormat;
@property (nonatomic, copy) NSString *ks_save;
@property (nonatomic, copy) NSString *ks_report;
@property (nonatomic, copy) NSString *ks_thirdPartyData;
@property (nonatomic, copy) NSString *ks_savedBooksCount;
@property (nonatomic, copy) NSString *ks_font;
@property (nonatomic, copy) NSString *ks_accountRecoveryEmail;
@property (nonatomic, copy) NSString *ks_bookManagementHint;
@property (nonatomic, copy) NSString *ks_all;
@property (nonatomic, copy) NSString *ks_enterProtagonist;
@property (nonatomic, copy) NSString *ks_privacyPolicy;
@property (nonatomic, copy) NSString *ks_aboveMaxScore;
@property (nonatomic, copy) NSString *ks_hot;
@property (nonatomic, copy) NSString *ks_topReads;
@property (nonatomic, copy) NSString *ks_ad;
@property (nonatomic, copy) NSString *ks_noCollections;
@property (nonatomic, copy) NSString *ks_uploadFeaturesHint;
@property (nonatomic, copy) NSString *ks_feedbackTime;
@property (nonatomic, copy) NSString *ks_noCacheToClear;
@property (nonatomic, copy) NSString *ks_bookCountFormat;
@property (nonatomic, copy) NSString *ks_narrationVoice;
@property (nonatomic, copy) NSString *ks_booklistDescription;
@property (nonatomic, copy) NSString *ks_enterText;
@property (nonatomic, copy) NSString *ks_fair;
@property (nonatomic, copy) NSString *ks_realistic;
@property (nonatomic, copy) NSString *ks_cacheCleared;
@property (nonatomic, copy) NSString *ks_shareVia;
@property (nonatomic, copy) NSString *ks_addToShelfConfirm;
@property (nonatomic, copy) NSString *ks_newest;
@property (nonatomic, copy) NSString *ks_notice;
@property (nonatomic, copy) NSString *ks_saving;
@property (nonatomic, copy) NSString *ks_serializing;
@property (nonatomic, copy) NSString *ks_bookCache;
@property (nonatomic, copy) NSString *ks_overLimit;
@property (nonatomic, copy) NSString *ks_otherError;
@property (nonatomic, copy) NSString *ks_unfavorited;
@property (nonatomic, copy) NSString *ks_booksCount;
@property (nonatomic, copy) NSString *ks_selectRequestType;
@property (nonatomic, copy) NSString *ks_alreadyInShelf;
@property (nonatomic, copy) NSString *ks_male;
@property (nonatomic, copy) NSString *ks_passwordRecovered;
@property (nonatomic, copy) NSString *ks_reload;
@property (nonatomic, copy) NSString *ks_noBooklists;
@property (nonatomic, copy) NSString *ks_minutesAgo;
@property (nonatomic, copy) NSString *ks_myBooks;
@property (nonatomic, copy) NSString *ks_flipSpeed;
@property (nonatomic, copy) NSString *ks_noSynopsis;
@property (nonatomic, copy) NSString *ks_avatar;
@property (nonatomic, copy) NSString *ks_enterAuthorName;
@property (nonatomic, copy) NSString *ks_statusFormat;
@property (nonatomic, copy) NSString *ks_aboutVersion;
@property (nonatomic, copy) NSString *ks_ranking;
@property (nonatomic, copy) NSString *ks_titleFormat;
@property (nonatomic, copy) NSString *ks_downloaded;
@property (nonatomic, copy) NSString *ks_reset;
@property (nonatomic, copy) NSString *ks_setSpacingHint;
@property (nonatomic, copy) NSString *ks_selectTypeFirst;
@property (nonatomic, copy) NSString *ks_requiredField;
@property (nonatomic, copy) NSString *ks_communityRules;
@property (nonatomic, copy) NSString *ks_moreByAuthor;
@property (nonatomic, copy) NSString *ks_night;
@property (nonatomic, copy) NSString *ks_notNow;
@property (nonatomic, copy) NSString *ks_terrible;
@property (nonatomic, copy) NSString *ks_minutes;
@property (nonatomic, copy) NSString *ks_requiredBookField;
@property (nonatomic, copy) NSString *ks_pinned;
@property (nonatomic, copy) NSString *ks_hours;
@property (nonatomic, copy) NSString *ks_note;
@property (nonatomic, copy) NSString *ks_oneMinute;
@property (nonatomic, copy) NSString *ks_xingkai;
@property (nonatomic, copy) NSString *ks_userAgreement;
@property (nonatomic, copy) NSString *ks_searchSource;
@property (nonatomic, copy) NSString *ks_accountRecoveryPhone;
@property (nonatomic, copy) NSString *ks_requiredSourceUrl;
@property (nonatomic, copy) NSString *ks_accountCancel;
@property (nonatomic, copy) NSString *ks_bookDiscoverySource;
@property (nonatomic, copy) NSString *ks_retry;
@property (nonatomic, copy) NSString *ks_transcodingSource;
@property (nonatomic, copy) NSString *ks_average;
@property (nonatomic, copy) NSString *ks_favoriteLists;
@property (nonatomic, copy) NSString *ks_newNickname;
@property (nonatomic, copy) NSString *ks_replyComment;
@property (nonatomic, copy) NSString *ks_enterPhoneOrQQ;
@property (nonatomic, copy) NSString *ks_searchHistoryCleared;
@property (nonatomic, copy) NSString *ks_slower;
@property (nonatomic, copy) NSString *ks_faster;
@property (nonatomic, copy) NSString *ks_viewAllReviews;
@property (nonatomic, copy) NSString *ks_verificationCode;
@property (nonatomic, copy) NSString *ks_readProgress;
@property (nonatomic, copy) NSString *ks_exitReading;
@property (nonatomic, copy) NSString *ks_feedbackStatus;
@property (nonatomic, copy) NSString *ks_enterCurrentPassword;
@property (nonatomic, copy) NSString *ks_shelf;
@property (nonatomic, copy) NSString *ks_logoutWarning;
@property (nonatomic, copy) NSString *ks_rate5Stars;
@property (nonatomic, copy) NSString *ks_currentPassword;
@property (nonatomic, copy) NSString *ks_listDescription;
@property (nonatomic, copy) NSString *ks_scrollMode;
@property (nonatomic, copy) NSString *ks_searchHistory;
@property (nonatomic, copy) NSString *ks_readHistory;
@property (nonatomic, copy) NSString *ks_enableNotifications;
@property (nonatomic, copy) NSString *ks_comment;
@property (nonatomic, copy) NSString *ks_writeComment;
@property (nonatomic, copy) NSString *ks_choicePercentage;
@property (nonatomic, copy) NSString *ks_requestInfo;
@property (nonatomic, copy) NSString *ks_profile;
@property (nonatomic, copy) NSString *ks_enterComment;
@property (nonatomic, copy) NSString *ks_noBookstoreData;
@property (nonatomic, copy) NSString *ks_autoReadEnded;
@property (nonatomic, copy) NSString *ks_copiedToShare;
@property (nonatomic, copy) NSString *ks_sensitiveContent;
@property (nonatomic, copy) NSString *ks_enterContactInfo;
@property (nonatomic, copy) NSString *ks_submit;
@property (nonatomic, copy) NSString *ks_linghuiFont;
@property (nonatomic, copy) NSString *ks_copyLinkHint;
@property (nonatomic, copy) NSString *ks_removeFailed;
@property (nonatomic, copy) NSString *ks_trending;
@property (nonatomic, copy) NSString *ks_qrInstall;
@property (nonatomic, copy) NSString *ks_management;
@property (nonatomic, copy) NSString *ks_clearHistoryWarning;
@property (nonatomic, copy) NSString *ks_confirmBlockUser;
@property (nonatomic, copy) NSString *ks_requestHistory;
@property (nonatomic, copy) NSString *ks_invalidFormat;
@property (nonatomic, copy) NSString *ks_originalPoster;
@property (nonatomic, copy) NSString *ks_userComment;
@property (nonatomic, copy) NSString *ks_source;
@property (nonatomic, copy) NSString *ks_complain;
@property (nonatomic, copy) NSString *ks_sourcesCount;
@property (nonatomic, copy) NSString *ks_lantingHei;
@property (nonatomic, copy) NSString *ks_notes;
@property (nonatomic, copy) NSString *ks_privacyTerms;
@property (nonatomic, copy) NSString *ks_noCategories;
@property (nonatomic, copy) NSString *ks_coverMode;
@property (nonatomic, copy) NSString *ks_rating;
@property (nonatomic, copy) NSString *ks_replySuccess;
@property (nonatomic, copy) NSString *ks_changeNickname;
@property (nonatomic, copy) NSString *ks_recommendations;
@property (nonatomic, copy) NSString *ks_send;
@property (nonatomic, copy) NSString *ks_open;
@property (nonatomic, copy) NSString *ks_currentlyReading;
@property (nonatomic, copy) NSString *ks_nightCare;
@property (nonatomic, copy) NSString *ks_feedbackContent;
@property (nonatomic, copy) NSString *ks_female;
@property (nonatomic, copy) NSString *ks_descending;
@property (nonatomic, copy) NSString *ks_versionInfo;
@property (nonatomic, copy) NSString *ks_preferredGenres;
@property (nonatomic, copy) NSString *ks_updateAlerts;
@property (nonatomic, copy) NSString *ks_deletedSuccess;
@property (nonatomic, copy) NSString *ks_notificationSettings;
@property (nonatomic, copy) NSString *ks_noReadHistory;
@property (nonatomic, copy) NSString *ks_giveFeedback;
@property (nonatomic, copy) NSString *ks_edit;
@property (nonatomic, copy) NSString *ks_continue;
@property (nonatomic, copy) NSString *ks_savedBooks;
@property (nonatomic, copy) NSString *ks_pauseReading;
@property (nonatomic, copy) NSString *ks_chaptersCount;
@property (nonatomic, copy) NSString *ks_validEmail;
@property (nonatomic, copy) NSString *ks_newVersion;
@property (nonatomic, copy) NSString *ks_trendingSearches;
@property (nonatomic, copy) NSString *ks_post;
@property (nonatomic, copy) NSString *ks_changeLoginPassword;
@property (nonatomic, copy) NSString *ks_sourceFormat;
@property (nonatomic, copy) NSString *ks_contents;
@property (nonatomic, copy) NSString *ks_booksAndFavs;
@property (nonatomic, copy) NSString *ks_exitAutoTurn;
@property (nonatomic, copy) NSString *ks_validPhone;
@property (nonatomic, copy) NSString *ks_accountDeleted;
@property (nonatomic, copy) NSString *ks_enterEmail;
@property (nonatomic, copy) NSString *ks_noContents;
@property (nonatomic, copy) NSString *ks_submitted;
@property (nonatomic, copy) NSString *ks_countryCode;
@property (nonatomic, copy) NSString *ks_qrCodeSaved;
@property (nonatomic, copy) NSString *ks_adjustFilter;
@property (nonatomic, copy) NSString *ks_skipInSeconds;
@property (nonatomic, copy) NSString *ks_guide;
@property (nonatomic, copy) NSString *ks_validNewPassword;
@property (nonatomic, copy) NSString *ks_sourceUrl;
@property (nonatomic, copy) NSString *ks_minScoreError;
@property (nonatomic, copy) NSString *ks_tip;
@property (nonatomic, copy) NSString *ks_deleteBook;
@property (nonatomic, copy) NSString *ks_think;
@property (nonatomic, copy) NSString *ks_recoverPassword;
@property (nonatomic, copy) NSString *ks_newPasswordDifferent;
@property (nonatomic, copy) NSString *ks_eyeProtection;
@property (nonatomic, copy) NSString *ks_feedbackHistory;
@property (nonatomic, copy) NSString *ks_recentReads;
@property (nonatomic, copy) NSString *ks_login;
@property (nonatomic, copy) NSString *ks_ratingFormat;
@property (nonatomic, copy) NSString *ks_lishuFont;
@property (nonatomic, copy) NSString *ks_myRequests;
@property (nonatomic, copy) NSString *ks_favorite;
@property (nonatomic, copy) NSString *ks_requiredProtagonist;
@property (nonatomic, copy) NSString *ks_chapterError;
@property (nonatomic, copy) NSString *ks_nextChapters;
@property (nonatomic, copy) NSString *ks_deselect;
@property (nonatomic, copy) NSString *ks_removeFromShelf;
@property (nonatomic, copy) NSString *ks_selectSource;
@property (nonatomic, copy) NSString *ks_mySettings;
@property (nonatomic, copy) NSString *ks_unfavorite;
@property (nonatomic, copy) NSString *ks_networkError;
@property (nonatomic, copy) NSString *ks_addToShelf;
@property (nonatomic, copy) NSString *ks_freeReading;
@property (nonatomic, copy) NSString *ks_lastChapterPrompt;
@property (nonatomic, copy) NSString *ks_emptyFontName;
@property (nonatomic, copy) NSString *ks_less;
@property (nonatomic, copy) NSString *ks_username;
@property (nonatomic, copy) NSString *ks_reenterPassword;
@property (nonatomic, copy) NSString *ks_justNow;
@property (nonatomic, copy) NSString *ks_cachedStatus;
@property (nonatomic, copy) NSString *ks_remove;
@property (nonatomic, copy) NSString *ks_guideWelcome;
@property (nonatomic, copy) NSString *ks_loginNow;
@property (nonatomic, copy) NSString *ks_voice;
@property (nonatomic, copy) NSString *ks_clearNetworkCache;
@property (nonatomic, copy) NSString *ks_termsOfService;
@property (nonatomic, copy) NSString *ks_weibeiFont;
@property (nonatomic, copy) NSString *ks_noFeedbackHistory;
@property (nonatomic, copy) NSString *ks_logout;
@property (nonatomic, copy) NSString *ks_more;
@property (nonatomic, copy) NSString *ks_noBookData;
@property (nonatomic, copy) NSString *ks_button;
@property (nonatomic, copy) NSString *ks_download;
@property (nonatomic, copy) NSString *ks_listMode;
@property (nonatomic, copy) NSString *ks_bookstore;
@property (nonatomic, copy) NSString *ks_requestBook;
@property (nonatomic, copy) NSString *ks_historyFeature;
@property (nonatomic, copy) NSString *ks_updatedFormat;
@property (nonatomic, copy) NSString *ks_rateThisBook;
@property (nonatomic, copy) NSString *ks_viewOtherSources;
@property (nonatomic, copy) NSString *ks_myBooklists;
@property (nonatomic, copy) NSString *ks_updatedTime;
@property (nonatomic, copy) NSString *ks_hoursAgo;
@property (nonatomic, copy) NSString *ks_email;
@property (nonatomic, copy) NSString *ks_dayMode;
@property (nonatomic, copy) NSString *ks_go;
@property (nonatomic, copy) NSString *ks_view;
@property (nonatomic, copy) NSString *ks_avatarUploadSuccess;
@property (nonatomic, copy) NSString *ks_required;
@property (nonatomic, copy) NSString *ks_qualityReviews;
@property (nonatomic, copy) NSString *ks_deleteFailed;
@property (nonatomic, copy) NSString *ks_migrationNotice;
@property (nonatomic, copy) NSString *ks_userSettings;
@property (nonatomic, copy) NSString *ks_processingStatus;
@property (nonatomic, copy) NSString *ks_likesCount;
@property (nonatomic, copy) NSString *ks_shareWithFriends;
@property (nonatomic, copy) NSString *ks_allDownloaded;
@property (nonatomic, copy) NSString *ks_booksAndFavorites;
@property (nonatomic, copy) NSString *ks_savedToAlbum;
@property (nonatomic, copy) NSString *ks_startReading;
@property (nonatomic, copy) NSString *ks_nightMode;
@property (nonatomic, copy) NSString *ks_selectType;
@property (nonatomic, copy) NSString *ks_enterBookTitle;
@property (nonatomic, copy) NSString *ks_ended;
@property (nonatomic, copy) NSString *ks_synced;
@property (nonatomic, copy) NSString *ks_authorLists;
@property (nonatomic, copy) NSString *ks_addedToShelf;
@property (nonatomic, copy) NSString *ks_favoriteSuccess;
@property (nonatomic, copy) NSString *ks_getVerificationCode;
@property (nonatomic, copy) NSString *ks_unreadStatus;
@property (nonatomic, copy) NSString *ks_violation;
@property (nonatomic, copy) NSString *ks_qrInstallStep;
@property (nonatomic, copy) NSString *ks_viewMyShelf;
@property (nonatomic, copy) NSString *ks_spacingTooLong;
@property (nonatomic, copy) NSString *ks_communityGuidelines;
@property (nonatomic, copy) NSString *ks_repliedStatus;
@property (nonatomic, copy) NSString *ks_selectBook;
@property (nonatomic, copy) NSString *ks_confirmCacheClear;
@property (nonatomic, copy) NSString *ks_fifteenMinutes;
@property (nonatomic, copy) NSString *ks_shelfSorting;
@property (nonatomic, copy) NSString *ks_enterPassword;
@property (nonatomic, copy) NSString *ks_nicknameTooLong;
@property (nonatomic, copy) NSString *ks_noRankings;
@property (nonatomic, copy) NSString *ks_pageNumber;
@property (nonatomic, copy) NSString *ks_cancel;
@property (nonatomic, copy) NSString *ks_reject;
@property (nonatomic, copy) NSString *ks_yuppieFont;
@property (nonatomic, copy) NSString *ks_pornographic;
@property (nonatomic, copy) NSString *ks_loadFailedPrompt;
@property (nonatomic, copy) NSString *ks_audiobook;
@property (nonatomic, copy) NSString *ks_savingStatus;
@property (nonatomic, copy) NSString *ks_enterRequiredInfo;
@property (nonatomic, copy) NSString *ks_termsAndPrivacy;
@property (nonatomic, copy) NSString *ks_enterNickname;
@property (nonatomic, copy) NSString *ks_auto;
@property (nonatomic, copy) NSString *ks_latestUpdate;
@property (nonatomic, copy) NSString *ks_bindInviteCode;
@property (nonatomic, copy) NSString *ks_inviteCodeBound;
@property (nonatomic, copy) NSString *ks_enterInviteCode;
@property (nonatomic, copy) NSString *ks_language;
@property (nonatomic, copy) NSString *ks_confirmDeleteBooks;
@property (nonatomic, copy) NSString *ks_firstPageReached;
@property (nonatomic, copy) NSString *ks_autoReadNotice;
@property (nonatomic, copy) NSString *ks_gotitLa;
@property (nonatomic, copy) NSString *ks_bookNotFound;
@property (nonatomic, copy) NSString *ks_registrationSuccess;
@property (nonatomic, copy) NSString *ks_contactSupport;
@property (nonatomic, copy) NSString *ks_userName;
@property (nonatomic, copy) NSString *ks_expiryDate;
@property (nonatomic, copy) NSString *ks_paymentHistory;
@property (nonatomic, copy) NSString *ks_submitOrder;
@property (nonatomic, copy) NSString *ks_subscribeRenew;
@property (nonatomic, copy) NSString *ks_buyCoins;
@property (nonatomic, copy) NSString *ks_coinHistory;
@property (nonatomic, copy) NSString *ks_topBooks;
@property (nonatomic, copy) NSString *ks_bestsellers;
@property (nonatomic, copy) NSString *ks_allRankings;
@property (nonatomic, copy) NSString *ks_addFavorites;
@property (nonatomic, copy) NSString *ks_goToBookstore;
@property (nonatomic, copy) NSString *ks_chapterLoadFailed;
@property (nonatomic, copy) NSString *ks_startCache;
@property (nonatomic, copy) NSString *ks_cachePrompt;
@property (nonatomic, copy) NSString *ks_cachingProgress;
@property (nonatomic, copy) NSString *ks_confirmDeleteBook;
@property (nonatomic, copy) NSString *ks_nextTime;
@property (nonatomic, copy) NSString *ks_chapterChangeError;
@property (nonatomic, copy) NSString *ks_passwordNewMismatch;
@property (nonatomic, copy) NSString *ks_privacyPrivacy;

+ (NSString *)ks_back;
+ (NSString *)ks_under10kWords;
+ (NSString *)ks_popular;
+ (NSString *)ks_disclaimer;
+ (NSString *)ks_reading;
+ (NSString *)ks_uniqueNicknameRequired;
+ (NSString *)ks_urlProtagonistFormat;
+ (NSString *)ks_settings;
+ (NSString *)ks_noSearchHistory;
+ (NSString *)ks_reviews;
+ (NSString *)ks_netCacheCleared;
+ (NSString *)ks_enterTitleOrAuthor;
+ (NSString *)ks_clearCache;
+ (NSString *)ks_pointsSuffix;
+ (NSString *)ks_selectedCount;
+ (NSString *)ks_fiveStar;
+ (NSString *)ks_home;
+ (NSString *)ks_read;
+ (NSString *)ks_unavailable;
+ (NSString *)ks_unfold;
+ (NSString *)ks_general;
+ (NSString *)ks_enterPhoneNumber;
+ (NSString *)ks_sortBy;
+ (NSString *)ks_clear;
+ (NSString *)ks_categories;
+ (NSString *)ks_noResults;
+ (NSString *)ks_guidelines;
+ (NSString *)ks_agreementHint;
+ (NSString *)ks_enterNewPassword;
+ (NSString *)ks_maxScoreError;
+ (NSString *)ks_gotIt;
+ (NSString *)ks_violationProcessTime;
+ (NSString *)ks_flip;
+ (NSString *)ks_readsFormat;
+ (NSString *)ks_signUp;
+ (NSString *)ks_pending;
+ (NSString *)ks_poor;
+ (NSString *)ks_cellularDownloadWarning;
+ (NSString *)ks_awesome;
+ (NSString *)ks_active;
+ (NSString *)ks_clearBookCacheConfirm;
+ (NSString *)ks_yesterdayTimeFormat;
+ (NSString *)ks_searchBooksHint;
+ (NSString *)ks_rateUsPrompt;
+ (NSString *)ks_clearAllChaptersWarning;
+ (NSString *)ks_uploadSuccess;
+ (NSString *)ks_feedbackOpinion;
+ (NSString *)ks_chapterListError;
+ (NSString *)ks_updateNow;
+ (NSString *)ks_requestFulfilledStatus;
+ (NSString *)ks_readingPreferenceHint;
+ (NSString *)ks_replySuffix;
+ (NSString *)ks_block;
+ (NSString *)ks_later;
+ (NSString *)ks_rateUs;
+ (NSString *)ks_searchResults;
+ (NSString *)ks_blueLightFilter;
+ (NSString *)ks_eyeCareMode;
+ (NSString *)ks_yes;
+ (NSString *)ks_ok;
+ (NSString *)ks_belowMinScore;
+ (NSString *)ks_changeCoverConfirm;
+ (NSString *)ks_noCachedBooks;
+ (NSString *)ks_me;
+ (NSString *)ks_verificationCodeSent;
+ (NSString *)ks_notDownloaded;
+ (NSString *)ks_noReadingHistory;
+ (NSString *)ks_readingModesHint;
+ (NSString *)ks_rateFirst;
+ (NSString *)ks_feedback;
+ (NSString *)ks_noBooks;
+ (NSString *)ks_requiredAuthorField;
+ (NSString *)ks_thirtyMinutes;
+ (NSString *)ks_blockSuccess;
+ (NSString *)ks_wordCountFormat;
+ (NSString *)ks_share;
+ (NSString *)ks_peopleSuffix;
+ (NSString *)ks_tenThousandSuffix;
+ (NSString *)ks_tenThousand;
+ (NSString *)ks_phone;
+ (NSString *)ks_clearBookCache;
+ (NSString *)ks_totalCount;
+ (NSString *)ks_timer;
+ (NSString *)ks_deleteAccount;
+ (NSString *)ks_qrCodeScanHint;
+ (NSString *)ks_readingMinutes;
+ (NSString *)ks_noRequests;
+ (NSString *)ks_emptyChapter;
+ (NSString *)ks_invalidPassword;
+ (NSString *)ks_empty;
+ (NSString *)ks_skip;
+ (NSString *)ks_passwordChanged;
+ (NSString *)ks_unread;
+ (NSString *)ks_syncShelf;
+ (NSString *)ks_searchAll;
+ (NSString *)ks_minMaxScoreError;
+ (NSString *)ks_details;
+ (NSString *)ks_writeReview;
+ (NSString *)ks_contact;
+ (NSString *)ks_sixtyMinutes;
+ (NSString *)ks_completed;
+ (NSString *)ks_reply;
+ (NSString *)ks_about;
+ (NSString *)ks_removedFromShelf;
+ (NSString *)ks_chapterFormat;
+ (NSString *)ks_enterSearchText;
+ (NSString *)ks_saveForLater;
+ (NSString *)ks_viewAllReplies;
+ (NSString *)ks_chapters;
+ (NSString *)ks_bookmarks;
+ (NSString *)ks_passwordNewMismatch;
+ (NSString *)ks_noneSelected;
+ (NSString *)ks_heitiFont;
+ (NSString *)ks_history;
+ (NSString *)ks_book;
+ (NSString *)ks_addToShelfFailed;
+ (NSString *)ks_registrationAgreement;
+ (NSString *)ks_speed;
+ (NSString *)ks_standard;
+ (NSString *)ks_nickname;
+ (NSString *)ks_byAuthorFormat;
+ (NSString *)ks_quickRate;
+ (NSString *)ks_viewBookstore;
+ (NSString *)ks_fontError;
+ (NSString *)ks_terms;
+ (NSString *)ks_confirm;
+ (NSString *)ks_lastChapterReached;
+ (NSString *)ks_enterOriginalUrl;
+ (NSString *)ks_commentGuidelines;
+ (NSString *)ks_enterVerificationCode;
+ (NSString *)ks_noUpdates;
+ (NSString *)ks_systemFont;
+ (NSString *)ks_disgusting;
+ (NSString *)ks_yesterday;
+ (NSString *)ks_ongoing;
+ (NSString *)ks_cached;
+ (NSString *)ks_viewReviews;
+ (NSString *)ks_xingkaiBold;
+ (NSString *)ks_accountRecoveryNotice;
+ (NSString *)ks_qrCodeSaveFailed;
+ (NSString *)ks_ascending;
+ (NSString *)ks_store;
+ (NSString *)ks_describeIssuePrompt;
+ (NSString *)ks_readPercentage;
+ (NSString *)ks_changePassword;
+ (NSString *)ks_delete;
+ (NSString *)ks_selectAll;
+ (NSString *)ks_bookTitleFormat;
+ (NSString *)ks_save;
+ (NSString *)ks_report;
+ (NSString *)ks_thirdPartyData;
+ (NSString *)ks_savedBooksCount;
+ (NSString *)ks_font;
+ (NSString *)ks_accountRecoveryEmail;
+ (NSString *)ks_bookManagementHint;
+ (NSString *)ks_all;
+ (NSString *)ks_enterProtagonist;
+ (NSString *)ks_privacyPolicy;
+ (NSString *)ks_aboveMaxScore;
+ (NSString *)ks_hot;
+ (NSString *)ks_topReads;
+ (NSString *)ks_ad;
+ (NSString *)ks_noCollections;
+ (NSString *)ks_uploadFeaturesHint;
+ (NSString *)ks_feedbackTime;
+ (NSString *)ks_noCacheToClear;
+ (NSString *)ks_bookCountFormat;
+ (NSString *)ks_narrationVoice;
+ (NSString *)ks_booklistDescription;
+ (NSString *)ks_enterText;
+ (NSString *)ks_fair;
+ (NSString *)ks_realistic;
+ (NSString *)ks_cacheCleared;
+ (NSString *)ks_shareVia;
+ (NSString *)ks_addToShelfConfirm;
+ (NSString *)ks_newest;
+ (NSString *)ks_notice;
+ (NSString *)ks_saving;
+ (NSString *)ks_serializing;
+ (NSString *)ks_bookCache;
+ (NSString *)ks_overLimit;
+ (NSString *)ks_otherError;
+ (NSString *)ks_unfavorited;
+ (NSString *)ks_booksCount;
+ (NSString *)ks_selectRequestType;
+ (NSString *)ks_alreadyInShelf;
+ (NSString *)ks_male;
+ (NSString *)ks_passwordRecovered;
+ (NSString *)ks_reload;
+ (NSString *)ks_noBooklists;
+ (NSString *)ks_minutesAgo;
+ (NSString *)ks_myBooks;
+ (NSString *)ks_flipSpeed;
+ (NSString *)ks_noSynopsis;
+ (NSString *)ks_avatar;
+ (NSString *)ks_enterAuthorName;
+ (NSString *)ks_statusFormat;
+ (NSString *)ks_aboutVersion;
+ (NSString *)ks_ranking;
+ (NSString *)ks_titleFormat;
+ (NSString *)ks_downloaded;
+ (NSString *)ks_reset;
+ (NSString *)ks_setSpacingHint;
+ (NSString *)ks_selectTypeFirst;
+ (NSString *)ks_requiredField;
+ (NSString *)ks_communityRules;
+ (NSString *)ks_moreByAuthor;
+ (NSString *)ks_night;
+ (NSString *)ks_notNow;
+ (NSString *)ks_terrible;
+ (NSString *)ks_minutes;
+ (NSString *)ks_requiredBookField;
+ (NSString *)ks_pinned;
+ (NSString *)ks_hours;
+ (NSString *)ks_note;
+ (NSString *)ks_oneMinute;
+ (NSString *)ks_xingkai;
+ (NSString *)ks_userAgreement;
+ (NSString *)ks_searchSource;
+ (NSString *)ks_accountRecoveryPhone;
+ (NSString *)ks_requiredSourceUrl;
+ (NSString *)ks_accountCancel;
+ (NSString *)ks_bookDiscoverySource;
+ (NSString *)ks_retry;
+ (NSString *)ks_transcodingSource;
+ (NSString *)ks_average;
+ (NSString *)ks_favoriteLists;
+ (NSString *)ks_newNickname;
+ (NSString *)ks_replyComment;
+ (NSString *)ks_enterPhoneOrQQ;
+ (NSString *)ks_searchHistoryCleared;
+ (NSString *)ks_slower;
+ (NSString *)ks_faster;
+ (NSString *)ks_viewAllReviews;
+ (NSString *)ks_verificationCode;
+ (NSString *)ks_readProgress;
+ (NSString *)ks_exitReading;
+ (NSString *)ks_feedbackStatus;
+ (NSString *)ks_enterCurrentPassword;
+ (NSString *)ks_shelf;
+ (NSString *)ks_logoutWarning;
+ (NSString *)ks_rate5Stars;
+ (NSString *)ks_currentPassword;
+ (NSString *)ks_listDescription;
+ (NSString *)ks_scrollMode;
+ (NSString *)ks_searchHistory;
+ (NSString *)ks_readHistory;
+ (NSString *)ks_enableNotifications;
+ (NSString *)ks_comment;
+ (NSString *)ks_writeComment;
+ (NSString *)ks_choicePercentage;
+ (NSString *)ks_requestInfo;
+ (NSString *)ks_profile;
+ (NSString *)ks_enterComment;
+ (NSString *)ks_noBookstoreData;
+ (NSString *)ks_autoReadEnded;
+ (NSString *)ks_copiedToShare;
+ (NSString *)ks_sensitiveContent;
+ (NSString *)ks_enterContactInfo;
+ (NSString *)ks_submit;
+ (NSString *)ks_linghuiFont;
+ (NSString *)ks_copyLinkHint;
+ (NSString *)ks_removeFailed;
+ (NSString *)ks_trending;
+ (NSString *)ks_qrInstall;
+ (NSString *)ks_management;
+ (NSString *)ks_clearHistoryWarning;
+ (NSString *)ks_confirmBlockUser;
+ (NSString *)ks_requestHistory;
+ (NSString *)ks_invalidFormat;
+ (NSString *)ks_originalPoster;
+ (NSString *)ks_userComment;
+ (NSString *)ks_source;
+ (NSString *)ks_complain;
+ (NSString *)ks_sourcesCount;
+ (NSString *)ks_lantingHei;
+ (NSString *)ks_notes;
+ (NSString *)ks_privacyTerms;
+ (NSString *)ks_noCategories;
+ (NSString *)ks_coverMode;
+ (NSString *)ks_rating;
+ (NSString *)ks_replySuccess;
+ (NSString *)ks_changeNickname;
+ (NSString *)ks_recommendations;
+ (NSString *)ks_send;
+ (NSString *)ks_open;
+ (NSString *)ks_currentlyReading;
+ (NSString *)ks_nightCare;
+ (NSString *)ks_feedbackContent;
+ (NSString *)ks_female;
+ (NSString *)ks_descending;
+ (NSString *)ks_versionInfo;
+ (NSString *)ks_preferredGenres;
+ (NSString *)ks_updateAlerts;
+ (NSString *)ks_deletedSuccess;
+ (NSString *)ks_notificationSettings;
+ (NSString *)ks_noReadHistory;
+ (NSString *)ks_giveFeedback;
+ (NSString *)ks_edit;
+ (NSString *)ks_continue;
+ (NSString *)ks_savedBooks;
+ (NSString *)ks_pauseReading;
+ (NSString *)ks_chaptersCount;
+ (NSString *)ks_validEmail;
+ (NSString *)ks_newVersion;
+ (NSString *)ks_trendingSearches;
+ (NSString *)ks_post;
+ (NSString *)ks_changeLoginPassword;
+ (NSString *)ks_sourceFormat;
+ (NSString *)ks_contents;
+ (NSString *)ks_booksAndFavs;
+ (NSString *)ks_exitAutoTurn;
+ (NSString *)ks_validPhone;
+ (NSString *)ks_accountDeleted;
+ (NSString *)ks_enterEmail;
+ (NSString *)ks_noContents;
+ (NSString *)ks_submitted;
+ (NSString *)ks_countryCode;
+ (NSString *)ks_qrCodeSaved;
+ (NSString *)ks_adjustFilter;
+ (NSString *)ks_skipInSeconds;
+ (NSString *)ks_guide;
+ (NSString *)ks_validNewPassword;
+ (NSString *)ks_sourceUrl;
+ (NSString *)ks_minScoreError;
+ (NSString *)ks_tip;
+ (NSString *)ks_deleteBook;
+ (NSString *)ks_think;
+ (NSString *)ks_recoverPassword;
+ (NSString *)ks_newPasswordDifferent;
+ (NSString *)ks_eyeProtection;
+ (NSString *)ks_feedbackHistory;
+ (NSString *)ks_recentReads;
+ (NSString *)ks_login;
+ (NSString *)ks_ratingFormat;
+ (NSString *)ks_lishuFont;
+ (NSString *)ks_myRequests;
+ (NSString *)ks_favorite;
+ (NSString *)ks_requiredProtagonist;
+ (NSString *)ks_chapterError;
+ (NSString *)ks_nextChapters;
+ (NSString *)ks_deselect;
+ (NSString *)ks_removeFromShelf;
+ (NSString *)ks_selectSource;
+ (NSString *)ks_mySettings;
+ (NSString *)ks_unfavorite;
+ (NSString *)ks_networkError;
+ (NSString *)ks_addToShelf;
+ (NSString *)ks_freeReading;
+ (NSString *)ks_lastChapterPrompt;
+ (NSString *)ks_emptyFontName;
+ (NSString *)ks_less;
+ (NSString *)ks_username;
+ (NSString *)ks_reenterPassword;
+ (NSString *)ks_justNow;
+ (NSString *)ks_cachedStatus;
+ (NSString *)ks_remove;
+ (NSString *)ks_guideWelcome;
+ (NSString *)ks_loginNow;
+ (NSString *)ks_voice;
+ (NSString *)ks_clearNetworkCache;
+ (NSString *)ks_termsOfService;
+ (NSString *)ks_weibeiFont;
+ (NSString *)ks_noFeedbackHistory;
+ (NSString *)ks_logout;
+ (NSString *)ks_more;
+ (NSString *)ks_noBookData;
+ (NSString *)ks_button;
+ (NSString *)ks_download;
+ (NSString *)ks_listMode;
+ (NSString *)ks_bookstore;
+ (NSString *)ks_requestBook;
+ (NSString *)ks_historyFeature;
+ (NSString *)ks_updatedFormat;
+ (NSString *)ks_rateThisBook;
+ (NSString *)ks_viewOtherSources;
+ (NSString *)ks_myBooklists;
+ (NSString *)ks_updatedTime;
+ (NSString *)ks_hoursAgo;
+ (NSString *)ks_email;
+ (NSString *)ks_dayMode;
+ (NSString *)ks_go;
+ (NSString *)ks_view;
+ (NSString *)ks_avatarUploadSuccess;
+ (NSString *)ks_required;
+ (NSString *)ks_qualityReviews;
+ (NSString *)ks_deleteFailed;
+ (NSString *)ks_migrationNotice;
+ (NSString *)ks_userSettings;
+ (NSString *)ks_processingStatus;
+ (NSString *)ks_likesCount;
+ (NSString *)ks_shareWithFriends;
+ (NSString *)ks_allDownloaded;
+ (NSString *)ks_booksAndFavorites;
+ (NSString *)ks_savedToAlbum;
+ (NSString *)ks_startReading;
+ (NSString *)ks_nightMode;
+ (NSString *)ks_selectType;
+ (NSString *)ks_enterBookTitle;
+ (NSString *)ks_ended;
+ (NSString *)ks_synced;
+ (NSString *)ks_authorLists;
+ (NSString *)ks_addedToShelf;
+ (NSString *)ks_favoriteSuccess;
+ (NSString *)ks_getVerificationCode;
+ (NSString *)ks_unreadStatus;
+ (NSString *)ks_violation;
+ (NSString *)ks_qrInstallStep;
+ (NSString *)ks_viewMyShelf;
+ (NSString *)ks_spacingTooLong;
+ (NSString *)ks_communityGuidelines;
+ (NSString *)ks_repliedStatus;
+ (NSString *)ks_selectBook;
+ (NSString *)ks_confirmCacheClear;
+ (NSString *)ks_fifteenMinutes;
+ (NSString *)ks_shelfSorting;
+ (NSString *)ks_enterPassword;
+ (NSString *)ks_nicknameTooLong;
+ (NSString *)ks_noRankings;
+ (NSString *)ks_pageNumber;
+ (NSString *)ks_cancel;
+ (NSString *)ks_reject;
+ (NSString *)ks_yuppieFont;
+ (NSString *)ks_pornographic;
+ (NSString *)ks_loadFailedPrompt;
+ (NSString *)ks_audiobook;
+ (NSString *)ks_savingStatus;
+ (NSString *)ks_enterRequiredInfo;
+ (NSString *)ks_termsAndPrivacy;
+ (NSString *)ks_enterNickname;
+ (NSString *)ks_auto;
+ (NSString *)ks_latestUpdate;
+ (NSString *)ks_bindInviteCode;
+ (NSString *)ks_inviteCodeBound;
+ (NSString *)ks_enterInviteCode;
+ (NSString *)ks_language;
+ (NSString *)ks_confirmDeleteBooks;
+ (NSString *)ks_firstPageReached;
+ (NSString *)ks_autoReadNotice;
+ (NSString *)ks_gotitLa;
+ (NSString *)ks_bookNotFound;
+ (NSString *)ks_registrationSuccess;
+ (NSString *)ks_contactSupport;
+ (NSString *)ks_userName;
+ (NSString *)ks_expiryDate;
+ (NSString *)ks_paymentHistory;
+ (NSString *)ks_submitOrder;
+ (NSString *)ks_subscribeRenew;
+ (NSString *)ks_buyCoins;
+ (NSString *)ks_coinHistory;
+ (NSString *)ks_topBooks;
+ (NSString *)ks_bestsellers;
+ (NSString *)ks_allRankings;
+ (NSString *)ks_addFavorites;
+ (NSString *)ks_goToBookstore;
+ (NSString *)ks_chapterLoadFailed;
+ (NSString *)ks_startCache;
+ (NSString *)ks_cachePrompt;
+ (NSString *)ks_cachingProgress;
+ (NSString *)ks_confirmDeleteBook;
+ (NSString *)ks_nextTime;
+ (NSString *)ks_chapterChangeError;
+ (NSString *)ks_privacyPrivacy;
+ (NSString *)ks_passwordMismatch;
@end

NS_ASSUME_NONNULL_END
